window:
  dimensions:
    columns: 84
    lines: 26
  padding:
    x: 4
    y: 2
scrolling:
  multiplier: 1

font:
  normal:
    family: Fantasque Sans Mono
    style: Regular
  bold:
    family: Fantasque Sans Mono
    style: Bold
  italic:
    family: Fantasque Sans Mono
    style: Italic
  bold_italic:
    family: Fantasque Sans Mono
    style: Bold Italic
  size: 11.0

#background_opacity: 0.85

# Colors (Tomorrow Night)
colors:
  # Default colors
  primary:
    background: '#1d1f21'
    foreground: '#c5c8c6'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#1d1f21'
    cursor: '#ffffff'

  # Normal colors
  normal:
    black: '#2D2D2D'
    red: '#F2777A'
    green: '#92D192'
    yellow: '#FFD479'
    blue: '#6AB0F3'
    magenta: '#E1A6F2'
    cyan: '#76D4D6'
    white: '#B3B9C5'
  # Bright colors
  bright:
    black: '#777C85'
    red: '#F2777A'
    green: '#76D4D6'
    yellow: '#FFEEA6'
    blue: '#6AB0F3'
    magenta: '#E1A6F2'
    cyan: '#76D4D6'
    white: '#FFFFFF'
