window:
  dimensions:
    columns: 84
    lines: 26
  padding:
    x: 2
    y: 2
scrolling:
  multiplier: 1

font:
  normal:
    family: Monospace
    style: Regular
  bold:
    family: Monospace
    style: Bold
  italic:
    family: Monospace
    style: Italic
  bold_italic:
    family: Monospace
    style: Bold Italic
  size: 11.0

#background_opacity: 0.85

colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xbbc2cf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xecbe7b'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x46d9ff'
    white:   '0xbbc2cf'
