[window]
dimensions = { columns = 86, lines = 28 }
padding = { x = 4, y = 4 }

[scrolling]
multiplier = 1

[font]
normal = { family = "Iosevka NFM", style = "Regular" }
bold = { family = "Iosevka NFM", style = "Bold" }
italic = { family = "Iosevka NFM", style = "Italic" }
bold_italic = { family = "Iosevka NFM", style = "Bold Italic" }
size = 15

[colors.primary]
background = '#0d1117'
foreground = '#b3b1ad'

[colors.normal]
black   = '#484f58'
red     = '#ff7b72'
green   = '#3fb950'
yellow  = '#d29922'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#39c5cf'
white   = '#b1bac4'

[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#56d4dd'
white   = '#f0f6fc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'

