window:
  dimensions:
    columns: 84
    lines: 26
  padding:
    x: 4
    y: 2
scrolling:
  multiplier: 1

font:
  normal:
    family: Fantasque Sans Mono
    style: Regular
  bold:
    family: Fantasque Sans Mono
    style: Bold
  italic:
    family: Fantasque Sans Mono
    style: Italic
  bold_italic:
    family: Fantasque Sans Mono
    style: Bold Italic
  size: 11.0

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  cursor:
    text: '#f8f8f2'
    cursor: '#282a36'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  # Bright colors
  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'
