#!/bin/bash
# ~/.bashrc

[[ "$-" != *i* ]] && return

PS1='\[\e[31m\]\u\[\e[37m\]@\[\e[31m\]\h \[\e[33m\]\W \[\e[90m\]λ \[\e[39m\]'

HISTFILESIZE=10000
HISTCONTROL='erasedups'
HISTIGNORE='ls:history:exit'
PROMPT_COMMAND='history -a'

shopt -s histappend
shopt -s autocd

alias vi='nvim'
alias bat='nvim -R'
alias ls='ls --color=auto'
alias lsa='ls -a'
alias imv='nsxiv -a'

[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
