#!/bin/bash
# ~/.bashrc

[[ "$-" != *i* ]] && return

PS1='\[\e[31m\]\u\[\e[37m\]@\[\e[31m\]\h \[\e[33m\]\W \[\e[90m\]λ \[\e[39m\]'

HISTFILESIZE=10000
HISTCONTROL='erasedups'
PROMPT_COMMAND='history -a'

shopt -s histappend
shopt -s autocd

alias vi='nvim'
alias bat='nvim -R'
alias ls='ls --color=auto'
alias lsa='ls -a'
alias imv='nsxiv'

[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

bash_history_file=$(mktemp "$USER"_bash_historyXXXXXX)
awk 'NR == FNR { a[$0]++; next; }; ++b[$0] == a[$0]' \
    "$HOME/.bash_history" "$HOME/.bash_history" > "$bash_history_file"
mv "$bash_history_file" "$HOME/.bash_history"
unset bash_history_file
