#!/bin/bash
# ~/.xinitrc

[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr --rate 144.00
feh --bg-fill --no-fehbg "/mnt/archive/Images/Wallpapers/pastoral-painting.jpg"
xsetwacom --set 15 Rotate half
xsetwacom --set 18 Rotate half

dt() { echo -e "$(date +"%b %d")"; }
tm() { echo -e "^c#11111b^^b#f5e0dc^  $(date +"%a, %I:%M %p")  ^d^"; }

while true; do
    xsetroot -name "$(dt)  $(tm)"
    sleep 12 
done &

redshift -l 42.5:-71 -b 1.0:0.6 &
exec dwm
