#!/bin/sh

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-w")  while read file; do feh --bg-fill --no-fehbg "$file" & done ;;
"C-D")  while read file; do rm "$file" ; echo "deleted $file" & done ;;
esac

