#!/bin/sh

while read -r file
do
    case "$1" in
        "C-w")
                feh --bg-fill --no-fehbg "$file" ;;
        "C-D")
                rm "$file" ;;
        *)
                echo "Undefined Key"
                exit 1
                ;;
    esac
done
